import type { Ambassador, College, CommunityPost, Scholarship } from "@/types";

/**
 * Static fallback content rendered when the backend/database is unavailable
 * (e.g. local preview without MongoDB). Mirrors the backend seed data.
 */
export const sampleColleges: College[] = [
  {
    _id: "1",
    name: "Indian Institute of Technology Bombay",
    slug: "iit-bombay",
    shortName: "IIT Bombay",
    city: "Mumbai",
    state: "Maharashtra",
    type: "government",
    nirfRanking: 3,
    accreditation: ["NAAC A++", "NBA"],
    annualFeesInr: 230000,
    hostelFeesInr: 40000,
    about:
      "A premier engineering and research institution, consistently ranked among the top in India.",
    bannerUrl:
      "https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=1600&q=80",
    gallery: [],
    courses: ["B.Tech", "M.Tech", "PhD", "MBA"],
    facilities: ["Library", "Sports Complex", "Hostels", "Innovation Labs"],
    faculty: ["Distinguished professors"],
    placement: {
      averagePackageLpa: 21.8,
      highestPackageLpa: 210,
      placementRate: 95,
      topRecruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey"],
    },
    ratingAverage: 4.8,
    ratingCount: 1200,
    isFeatured: true,
  },
  {
    _id: "2",
    name: "Vellore Institute of Technology",
    slug: "vit-vellore",
    shortName: "VIT",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "private",
    nirfRanking: 11,
    accreditation: ["NAAC A++", "ABET"],
    annualFeesInr: 198000,
    hostelFeesInr: 75000,
    about: "A leading private university known for strong placements and a vibrant campus life.",
    bannerUrl:
      "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=1600&q=80",
    gallery: [],
    courses: ["B.Tech", "M.Tech", "BBA", "MCA"],
    facilities: ["Smart Classrooms", "Hostels", "Research Parks", "Stadium"],
    faculty: ["International faculty"],
    placement: {
      averagePackageLpa: 9.1,
      highestPackageLpa: 102,
      placementRate: 90,
      topRecruiters: ["Amazon", "TCS", "Cognizant", "Deloitte"],
    },
    ratingAverage: 4.4,
    ratingCount: 980,
    isFeatured: true,
  },
  {
    _id: "3",
    name: "Bennett University",
    slug: "bennett-university",
    shortName: "Bennett",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "private",
    nirfRanking: 90,
    accreditation: ["NAAC A"],
    annualFeesInr: 312000,
    hostelFeesInr: 145000,
    about: "A modern university founded by The Times Group with a focus on industry collaboration.",
    bannerUrl:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=1600&q=80",
    gallery: [],
    courses: ["B.Tech", "BBA", "B.A. Journalism", "LLB"],
    facilities: ["Media Labs", "Hostels", "Sports Arena", "Incubator"],
    faculty: ["Ivy-league trained faculty"],
    placement: {
      averagePackageLpa: 8.2,
      highestPackageLpa: 35,
      placementRate: 85,
      topRecruiters: ["Microsoft", "Times Internet", "EY", "Wipro"],
    },
    ratingAverage: 4.1,
    ratingCount: 320,
    isFeatured: false,
  },
];

export const sampleAmbassadors: Ambassador[] = [
  {
    id: "a1",
    name: "Aarav Sharma",
    email: "aarav@iitb.ac.in",
    role: "ambassador",
    verificationStatus: "verified",
    isEmailVerified: true,
    avatarUrl: "https://i.pravatar.cc/200?img=12",
    points: 1200,
    badges: ["Top Mentor"],
    college: sampleColleges[0],
    ambassador: {
      branch: "Computer Science",
      year: 3,
      cgpa: 9.1,
      languages: ["English", "Hindi", "Marathi"],
      about: "CSE junior at IIT Bombay. Happy to help with admissions and placements!",
      questionsAnswered: 142,
      followers: 980,
      rating: 4.9,
      ratingCount: 87,
    },
  },
  {
    id: "a2",
    name: "Priya Nair",
    email: "priya@vit.ac.in",
    role: "ambassador",
    verificationStatus: "verified",
    isEmailVerified: true,
    avatarUrl: "https://i.pravatar.cc/200?img=45",
    points: 900,
    badges: ["Contributor"],
    college: sampleColleges[1],
    ambassador: {
      branch: "Electronics",
      year: 4,
      cgpa: 8.7,
      languages: ["English", "Tamil", "Malayalam"],
      about: "Final-year ECE student. Ask me anything about hostel life and internships.",
      questionsAnswered: 96,
      followers: 640,
      rating: 4.7,
      ratingCount: 53,
    },
  },
  {
    id: "a3",
    name: "Rohan Mehta",
    email: "rohan@bennett.edu.in",
    role: "ambassador",
    verificationStatus: "verified",
    isEmailVerified: true,
    avatarUrl: "https://i.pravatar.cc/200?img=33",
    points: 700,
    badges: [],
    college: sampleColleges[2],
    ambassador: {
      branch: "Management",
      year: 2,
      cgpa: 8.2,
      languages: ["English", "Hindi"],
      about: "BBA student passionate about startups and campus clubs.",
      questionsAnswered: 61,
      followers: 410,
      rating: 4.6,
      ratingCount: 31,
    },
  },
  {
    id: "a4",
    name: "Sneha Reddy",
    email: "sneha@iitb.ac.in",
    role: "ambassador",
    verificationStatus: "verified",
    isEmailVerified: true,
    avatarUrl: "https://i.pravatar.cc/200?img=20",
    points: 1100,
    badges: ["Top Mentor"],
    college: sampleColleges[0],
    ambassador: {
      branch: "Mechanical",
      year: 3,
      cgpa: 8.9,
      languages: ["English", "Telugu", "Hindi"],
      about: "Mechanical engineering junior, GATE mentor and robotics enthusiast.",
      questionsAnswered: 88,
      followers: 720,
      rating: 4.8,
      ratingCount: 44,
    },
  },
];

export const sampleScholarships: Scholarship[] = [
  {
    _id: "s1",
    title: "National Means-cum-Merit Scholarship",
    slug: "nmms",
    provider: "Ministry of Education",
    type: "government",
    amountInr: 12000,
    category: ["general", "obc", "sc", "st"],
    maxIncomeInr: 350000,
    meritBased: true,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString(),
  },
  {
    _id: "s2",
    title: "Post Matric Scholarship (Maharashtra)",
    slug: "post-matric-maharashtra",
    provider: "Government of Maharashtra",
    type: "state",
    amountInr: 50000,
    category: ["sc", "st", "obc"],
    state: "Maharashtra",
    maxIncomeInr: 800000,
    meritBased: false,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30).toISOString(),
  },
  {
    _id: "s3",
    title: "Reliance Foundation Undergraduate Scholarship",
    slug: "reliance-foundation-ug",
    provider: "Reliance Foundation",
    type: "private",
    amountInr: 200000,
    category: ["general", "obc", "sc", "st", "ews"],
    maxIncomeInr: 1500000,
    meritBased: true,
    deadline: new Date(Date.now() + 1000 * 60 * 60 * 24 * 60).toISOString(),
  },
];

export const samplePosts: CommunityPost[] = [
  {
    _id: "p1",
    author: { _id: "a1", name: "Aarav Sharma", avatarUrl: "https://i.pravatar.cc/200?img=12", verificationStatus: "verified" },
    title: "How I cracked JEE Advanced while balancing boards",
    body: "Sharing my weekly study plan, mock test strategy, and the resources that actually helped.",
    category: "admission",
    tags: ["jee", "strategy", "iit"],
    likes: ["x", "y", "z"],
    commentCount: 24,
    createdAt: new Date().toISOString(),
  },
  {
    _id: "p2",
    author: { _id: "a2", name: "Priya Nair", avatarUrl: "https://i.pravatar.cc/200?img=45", verificationStatus: "verified" },
    title: "Hostel life at VIT — the honest review",
    body: "Mess food, room types, wifi, laundry and everything a fresher should know before joining.",
    category: "hostel",
    tags: ["hostel", "vit", "fresher"],
    likes: ["x", "y"],
    commentCount: 12,
    createdAt: new Date().toISOString(),
  },
];

export const successStories = [
  {
    name: "Ananya Gupta",
    college: "IIT Delhi",
    quote:
      "I was confused between three colleges. Chatting with a verified ambassador helped me pick the right one — best decision ever!",
    avatar: "https://i.pravatar.cc/200?img=5",
  },
  {
    name: "Karthik R",
    college: "NIT Trichy",
    quote:
      "The scholarship portal helped me find a private scholarship that covered half my fees. Forever grateful.",
    avatar: "https://i.pravatar.cc/200?img=15",
  },
  {
    name: "Fatima Khan",
    college: "BITS Pilani",
    quote:
      "Honest hostel and placement reviews from real students made my decision stress-free.",
    avatar: "https://i.pravatar.cc/200?img=25",
  },
];
